name: LineageOS building
on:
  push:
    branches:
      - cm-14.1
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: python2.7
        run: |
          sudo rm /bin/python
          sudo ln -s /bin/python2.7 /bin/python
      - name: run docker container
        uses: docker://jakesoso/cm_build:los14.1
        with:
          args: /bin/bash -c "bash build.sh"

